"""Netgen LVS 执行器"""
import os
import re
import json
import subprocess
from typing import Optional
from uuid import uuid4


class NetgenRunner:
    """执行 Netgen LVS 比对 (布局 SPICE vs 原理图 SPICE/网表)"""

    def __init__(self, config: dict):
        cfg = config.get("netgen", {})
        self.netgen_path = cfg.get("netgen_path", "netgen")
        self.timeout = cfg.get("timeout_seconds", 600)
        self.working_dir = cfg.get("working_dir", "./tmp/netgen_runs/")

    def execute(self, circuit_name: str, params: dict,
                analyses: Optional[list] = None) -> dict:
        """执行 Netgen LVS"""
        run_id = str(uuid4())[:8]
        run_dir = os.path.abspath(f"{self.working_dir}/{run_id}/")
        os.makedirs(run_dir, exist_ok=True)

        layout_file = params.get("layout_file")       # 布局侧 (提取 SPICE 或布线后网表 SPICE)
        schematic_file = params.get("schematic_file")  # 原理图侧 SPICE
        top_module = params.get("top_module", circuit_name)
        setup_content = params.get("setup_content", "")  # 可选: unmatch 规则 (tie/fill 单元)

        if not layout_file or not schematic_file:
            return {
                "success": False,
                "error": "layout_file 和 schematic_file 均为必需参数",
                "run_dir": run_dir,
            }
        if not os.path.exists(layout_file) or not os.path.exists(schematic_file):
            return {
                "success": False,
                "error": f"输入文件不存在: {layout_file} / {schematic_file}",
                "run_dir": run_dir,
            }

        # ---- 1. setup 文件 (必须存在; 内容可为空或含 unmatch 规则) ----
        setup_file = os.path.join(run_dir, "lvs_setup.tcl")
        with open(setup_file, "w") as f:
            f.write(setup_content)

        # ---- 2. 生成 Tcl 脚本 (lvs {file cell} {file cell} setup out -json) ----
        tcl_file = os.path.join(run_dir, "lvs.tcl")
        out_file = os.path.join(run_dir, "lvs.out")
        with open(tcl_file, "w") as f:
            f.write(
                "# Netgen LVS script — auto-generated by ic_agent_os\n"
                "set lvs_ignore_ports no\n"
                "set lvs_abort_on_failure no\n"
                "\n"
                f"lvs {{{schematic_file} {top_module}}} {{{layout_file} {top_module}}} "
                f"{setup_file} {out_file} -json\n"
                "quit\n"
            )

        # ---- 3. 执行 Netgen ----
        try:
            r = subprocess.run([self.netgen_path, "-batch", "source", tcl_file],
                               capture_output=True, text=True, timeout=self.timeout, cwd=run_dir)
        except subprocess.TimeoutExpired:
            return {"success": False, "lvs_match": False, "error": "netgen 超时", "run_dir": run_dir}

        output = r.stdout + r.stderr
        result = self._parse_output(output, out_file)

        return {
            "success": result["lvs_match"],
            "lvs_match": result["lvs_match"],
            "nets_matched": result["nets_matched"],
            "nets_total": result["nets_total"],
            "devices_matched": result["devices_matched"],
            "devices_total": result["devices_total"],
            "pins_matched": result["pins_matched"],
            "pins_total": result["pins_total"],
            "output": output[-1500:],
            "run_dir": run_dir,
            "out_file": out_file,
        }

    def _parse_output(self, output: str, out_file: str) -> dict:
        """解析 Netgen LVS 结果 (文本判定为准; 本机 netgen 的 -json 只有 pins 表,
        不含计数/判定字段, 不依赖)"""
        low = output.lower()
        lvs_match = "circuits match uniquely" in low or "netlists match uniquely" in low

        def _counts(kind: str):
            # "Number of nets: 12" 出现两次 (电路1/电路2); matched 按匹配时取电路1计数
            nums = [int(x) for x in re.findall(rf"Number of {kind}s?:\s*(\d+)", output, re.I)]
            if not nums:
                return 0, 0
            total = nums[0]
            return (total, total) if lvs_match else (max(0, total - max(0, nums[1] - nums[0])), total)

        nets_matched, nets_total = _counts("net")
        devices_matched, devices_total = _counts("device")
        pins_matched, pins_total = _counts("pin")

        return {
            "lvs_match": lvs_match,
            "nets_matched": nets_matched,
            "nets_total": nets_total,
            "devices_matched": devices_matched,
            "devices_total": devices_total,
            "pins_matched": pins_matched,
            "pins_total": pins_total,
        }
