"""Netgen LVS Adapter — 版图 vs 原理图一致性检查"""
import os, re, subprocess
from typing import Optional
from uuid import uuid4
from .runner import Backend


class NetgenRunner(Backend):
    """Netgen LVS 后端。

    流程:
        1. 生成 Netgen Tcl 脚本
        2. netgen -batch 执行
        3. 解析 LVS 结果 (match/fail)
    """

    def __init__(self, config: dict):
        cfg = config.get("netgen", {})
        self.netgen_path = cfg.get("netgen_path", "netgen")
        self.timeout = cfg.get("timeout_seconds", 600)
        self.working_dir = cfg.get("working_dir", "./tmp/netgen_runs/")

    def execute(self, circuit_name: str, params: dict,
                analyses: Optional[list] = None) -> dict:
        """执行 Netgen LVS"""
        run_id = str(uuid4())[:8]
        run_dir = os.path.abspath(f"{self.working_dir}/{run_id}/")
        os.makedirs(run_dir, exist_ok=True)

        layout_file = params.get("layout_file")       # GDS 或 SPICE (版图提取)
        schematic_file = params.get("schematic_file")  # 参考 SPICE 网表
        top_module = params.get("top_module", circuit_name)

        if not layout_file or not schematic_file:
            return {
                "success": False,
                "error": "layout_file 和 schematic_file 均为必需参数",
                "run_dir": run_dir,
            }

        # ---- 1. 生成 Tcl 脚本 ----
        tcl_content = self._generate_tcl(layout_file, schematic_file, top_module)
        tcl_file = os.path.join(run_dir, "lvs.tcl")
        with open(tcl_file, "w") as f:
            f.write(tcl_content)

        # ---- 2. 执行 Netgen ----
        cmd = [self.netgen_path, "-batch", "source", tcl_file]
        r = subprocess.run(cmd, capture_output=True, text=True,
                           timeout=self.timeout, cwd=run_dir)

        # ---- 3. 解析结果 ----
        output = r.stdout + r.stderr
        result = self._parse_output(output)

        return {
            "success": result["lvs_match"],
            "lvs_match": result["lvs_match"],
            "nets_matched": result["nets_matched"],
            "nets_total": result["nets_total"],
            "devices_matched": result["devices_matched"],
            "devices_total": result["devices_total"],
            "pins_matched": result["pins_matched"],
            "pins_total": result["pins_total"],
            "output": output[-3000:],
            "run_dir": run_dir,
        }

    def _generate_tcl(self, layout_file: str, schematic_file: str,
                      top_module: str) -> str:
        """生成 Netgen LVS Tcl 脚本"""
        layout = os.path.abspath(layout_file)
        sch = os.path.abspath(schematic_file)
        return (
            "# Netgen LVS script — auto-generated by ic_agent_os\n"
            "set lvs_ignore_ports no\n"
            "set lvs_abort_on_failure yes\n"
            "\n"
            f"readnet spice {sch}\n"
            f"readnet spice {layout} ${{{sch}}}.layout\n"
            "\n"
            f"lvs {{{top_module}}} {{{top_module}}} {sch}.lvs.out -json\n"
        )

    def _parse_output(self, output: str) -> dict:
        """解析 Netgen LVS 输出"""
        lvs_match = "Circuits match" in output or "circuits match uniquely" in output.lower()

        # 尝试解析 Netgen JSON 输出中的数字
        nets = re.findall(r"Net:\s*(\d+)\s*/\s*(\d+)", output)
        devs = re.findall(r"Device:\s*(\d+)\s*/\s*(\d+)", output)
        pins = re.findall(r"Pin:\s*(\d+)\s*/\s*(\d+)", output)

        return {
            "lvs_match": lvs_match,
            "nets_matched": int(nets[-1][0]) if nets else 0,
            "nets_total": int(nets[-1][1]) if nets else 0,
            "devices_matched": int(devs[-1][0]) if devs else 0,
            "devices_total": int(devs[-1][1]) if devs else 0,
            "pins_matched": int(pins[-1][0]) if pins else 0,
            "pins_total": int(pins[-1][1]) if pins else 0,
        }
